### ISSUE TITLE
Change experiences/educations/hobbies to use Jinja Templates

### ISSUE THREAD

**Issue by Diegogtz03** [Diegogtz03/PE-MLH-Portfolio#30]
I believe that using Jinja we can basically send data to our HTML file from out python that eventually could fetch information from a database/API.

I think we can achieve this by doing the following changes:

1. Strip down the elements that display the multiple experiences/educations/hobbies in their corresponding pages to a simple single element we can create multiple times...

So if we originally have something like this:
```html
<div class="hobbies-wrapper">
    <div class="hobby-card">
        <span> Walking <span>
    </div>
    <div class="hobby-card>
        <span> Coding <span>
    </div>
</div>
``` 
We would change it to something like this:

```html
<div class="hobbies-wrapper">
   {% for hobby in hobbies %}
      <div class="hobby-card">
         <span>{{ hobby.name }}</span>
      <div>
    {% endfor %}
</div>
``` 

In this case **'hobbies'** is a variable we send through __init__.py like this:

```python
hobbiesList = [
  {
    name: "Hello",
    description:...
    image:...
  }, 
  {
    name: "Coding",
    description:...
    image:...
 }]

render_template("hobbies.html", hobbies = hobbiesList);
```

**Comment by YeyoM** [comment]
I´ll take care of this issue!
