### ISSUE TITLE
👾 Fix bugs on responsive

### ISSUE THREAD

**Issue by Diegogtz03** [Diegogtz03/PE-MLH-Portfolio#35]
I ran the app on my phone and found some bugs:

- Sound effects won't play in phone's browser
- The contact me button gets hidden by safari's big search bar, so enable scroll?
- Touch events like the press 'SPACE', copying the email, and the click anywhere on the window to close the 'contact' info don't work on phone due to different event types
- Some pages get cut off in the sides

**Comment by YeyoM** [comment]
Found a bug in /experience page:
![image](https://github.com/Diegogtz03/PE-MLH-Portfolio/assets/76639199/216b8e80-62f8-4442-862a-4372f2d98c9f)

Found a bug in /projects page:
![image](https://github.com/Diegogtz03/PE-MLH-Portfolio/assets/76639199/57f7607a-08bd-4f2f-99b2-c3c5b4a8063a)

Found a bug in /about page:
![image](https://github.com/Diegogtz03/PE-MLH-Portfolio/assets/76639199/d0db2fc1-fd3e-43e9-a727-e58615be15c1)

I'll fix them on a different issue!
